package uno.zhuchen.agent.tools.ticket12306.model;
import lombok.AllArgsConstructor; import lombok.Builder; import lombok.Data; import lombok.NoArgsConstructor;
@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class InterlineTicketData {
    private String arriveTime;
    private String bedLevelInfo;
    private String controlledTrainFlag;
    private String countryFlag;
    private String dayDifference;
    private String dwFlag;
    private String endStationName;
    private String endStationTelecode;
    private String fromStationName;
    private String fromStationNo;
    private String fromStationTelecode;
    private String ggNum;
    private String grNum;
    private String isSupportCard;
    private String lishi;
    private String localArriveTime;
    private String localStartTime;
    private String qtNum;
    private String rwNum;
    private String rzNum;
    private String seatDiscountInfo;
    private String seatTypes;
    private String srrbNum;
    private String startStationName;
    private String startStationTelecode;
    private String startTime;
    private String startTrainDate;
    private String stationTrainCode;
    private String swzNum;
    private String toStationName;
    private String toStationNo;
    private String toStationTelecode;
    private String trainNo;
    private String trainSeatFeature;
    private String trmsTrainFlag;
    private String tzNum;
    private String wzNum;
    private String ybNum;
    private String ypInfo;
    private String ywNum;
    private String yzNum;
    private String zeNum;
    private String zyNum;
}
