spring:
  application:
    name: mcp-server

  ai:
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        name: amap-mcp-server
        version: 1.0.0
        type: SYNC

server:
  port: 8081

amap:
  api:
    key: 27eeeb30fd80e9f4f063c60027c4eade

logging:
  level:
    uno.zhuchen.agent.mcpserver: DEBUG
